name: moniepoint
description: "Coding test for Flutter engineer position"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_icon_snackbar: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/w300.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/w400.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/w500.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/w700.ttf
          weight: 700
